const DATA_GEAR = [
  { id: 'gear_0', name: '식양의 숨결 보조 견갑', part: 'component', set: 'set_shikyang', stat1: '의지', val1: 32, stat2: '지능', val2: 21, trait: { type: '궁극기 충전', val: 24.6 } },
  { id: 'gear_1', name: '식양의 숨결 충전 코어 · I', part: 'component', set: 'set_shikyang', stat1: '지능', val1: 32, stat2: '의지', val2: 21, trait: { type: '치유 효율', val: 20.7 } },
  { id: 'gear_2', name: '식양의 숨결 충전 코어', part: 'component', set: 'set_shikyang', stat1: '지능', val1: 32, stat2: '힘', val2: 21, trait: { type: '궁극기 충전', val: 24.6 } },
  { id: 'gear_3', name: '식양의 숨결 글러브 · I', part: 'glove', set: 'set_shikyang', stat1: '지능', val1: 65, stat2: '의지', val2: 43, trait: { type: '궁극기 충전', val: 20.5 } },
  { id: 'gear_4', name: '식양의 숨결 글러브', part: 'glove', set: 'set_shikyang', stat1: '지능', val1: 65, stat2: '힘', val2: 43, trait: { type: '궁극기 충전', val: 20.5 } },
  { id: 'gear_5', name: '식양의 숨결 장갑', part: 'armor', set: 'set_shikyang', stat1: '의지', val1: 87, stat2: '지능', val2: 58, trait: { type: '오리지늄 아츠', val: 20 } },
  { id: 'gear_6', name: '탁류 화염 절단기', part: 'component', set: 'set_joryu', stat1: '지능', val1: 32, stat2: '힘', val2: 21, trait: { type: '일반 공격 피해', val: 27.6 } },
  { id: 'gear_7', name: '현하 산소 공급 장치', part: 'component', set: 'set_joryu', stat1: '힘', val1: 32, stat2: '의지', val2: 21, trait: [{ type: '냉기 피해', val: 23 }, { type: '전기 피해', val: 23 }] },
  { id: 'gear_8', name: '조류의 물결 건틀릿', part: 'glove', set: 'set_joryu', stat1: '힘', val1: 65, stat2: '의지', val2: 43, trait: [{ type: '냉기 피해', val: 19.2 }, { type: '전기 피해', val: 19.2 }] },
  { id: 'gear_9', name: '낙조 경갑', part: 'armor', set: 'set_joryu', stat1: '지능', val1: 87, stat2: '힘', val2: 58, trait: { type: '궁극기 충전', val: 12.3 } },
  { id: 'gear_10', name: '응룡 50식 탐지기', part: 'armor', set: 'set_eungryong', stat1: '힘', val1: 32, stat2: '의지', val2: 21, trait: { type: '물리 피해', val: 23 } },
  { id: 'gear_11', name: '응룡 50식 단검 · I', part: 'component', set: 'set_eungryong', stat1: '지능', val1: 32, stat2: '힘', val2: 21, trait: { type: '모든 스킬 피해', val: 27.6 } },
  { id: 'gear_12', name: '응룡 50식 단검', part: 'component', set: 'set_eungryong', stat1: '의지', val1: 32, stat2: '민첩', val2: 21, trait: { type: '연계 스킬 피해', val: 41.4 } },
  { id: 'gear_13', name: '응룡 50식 글러브 · I', part: 'glove', set: 'set_eungryong', stat1: '의지', val1: 65, stat2: '민첩', val2: 43, trait: { type: '연계 스킬 피해', val: 34.5 } },
  { id: 'gear_14', name: '응룡 50식 글러브', part: 'glove', set: 'set_eungryong', stat1: '민첩', val1: 65, stat2: '지능', val2: 43, trait: { type: '연계 스킬 피해', val: 34.5 } },
  { id: 'gear_15', name: '응룡 50식 경갑', part: 'armor', set: 'set_eungryong', stat1: '의지', val1: 87, stat2: '힘', val2: 58, trait: { type: '모든 스킬 피해', val: 13.8 } },
  { id: 'gear_16', name: '응룡 50식 중갑', part: 'armor', set: 'set_eungryong', stat1: '힘', val1: 87, stat2: '의지', val2: 58, trait: { type: '물리 피해', val: 11.5 } },
  { id: 'gear_17', name: 'M. I. 경찰용 단검 · I', part: 'component', set: 'set_mi_police', stat1: '의지', val1: 32, stat2: '민첩', val2: 21, trait: { type: '배틀 스킬 피해', val: 41.4 } },
  { id: 'gear_18', name: 'M. I. 경찰용 단검', part: 'component', set: 'set_mi_police', stat1: '의지', val1: 32, stat2: '지능', val2: 21, trait: [{ type: '열기 피해', val: 23 }, { type: '자연 피해', val: 23 }] },
  { id: 'gear_19', name: 'M. I. 경찰용 도구 세트', part: 'component', set: 'set_mi_police', stat1: '지능', val1: 32, stat2: '민첩', val2: 21, trait: { type: '치명타 확률', val: 10.4 } },
  { id: 'gear_20', name: 'M. I. 경찰용 조준기', part: 'component', set: 'set_mi_police', stat1: '민첩', val1: 32, stat2: '힘', val2: 21, trait: { type: '배틀 스킬 피해', val: 41.4 } },
  { id: 'gear_21', name: 'M. I. 경찰용 수갑', part: 'component', set: 'set_mi_police', stat1: '힘', val1: 32, stat2: '의지', val2: 21, trait: [{ type: '냉기 피해', val: 41.4 }, { type: '전기 피해', val: 41.4 }] },
  { id: 'gear_22', name: 'M. I. 경찰용 팔찌 · I', part: 'glove', set: 'set_mi_police', stat1: '지능', val1: 65, stat2: '의지', val2: 43, trait: { type: '치명타 확률', val: 8.6 } },
  { id: 'gear_23', name: 'M. I. 경찰용 팔찌', part: 'glove', set: 'set_mi_police', stat1: '지능', val1: 65, stat2: '민첩', val2: 43, trait: { type: '일반 공격 피해', val: 23 } },
  { id: 'gear_24', name: 'M. I. 경찰용 장갑', part: 'glove', set: 'set_mi_police', stat1: '민첩', val1: 65, stat2: '힘', val2: 43, trait: { type: '배틀 스킬 피해', val: 34.5 } },
  { id: 'gear_25', name: 'M. I. 경찰용 망토 · II', part: 'armor', set: 'set_mi_police', stat1: '의지', val1: 87, stat2: '민첩', val2: 58, trait: { type: '배틀 스킬 피해', val: 20.7 } },
  { id: 'gear_26', name: 'M. I. 경찰용 망토 · I', part: 'armor', set: 'set_mi_police', stat1: '지능', val1: 87, stat2: '의지', val2: 58, trait: { type: '치명타 확률', val: 5.2 } },
  { id: 'gear_27', name: 'M. I. 경찰용 망토', part: 'armor', set: 'set_mi_police', stat1: '지능', val1: 87, stat2: '민첩', val2: 58, trait: { type: '일반 공격 피해', val: 13.8 } },
  { id: 'gear_28', name: 'M. I. 경찰용 방어구', part: 'armor', set: 'set_mi_police', stat1: '민첩', val1: 87, stat2: '힘', val2: 58, trait: { type: '오리지늄 아츠', val: 20 } },
  { id: 'gear_29', name: '열 작업용 전력 상자', part: 'component', set: 'set_heat_work', stat1: '의지', val1: 32, stat2: '지능', val2: 21, trait: { type: '오리지늄 아츠', val: 41 } },
  { id: 'gear_30', name: '열 작업용 에너지 저장함', part: 'component', set: 'set_heat_work', stat1: '힘', val1: 32, stat2: '민첩', val2: 21, trait: { type: '오리지늄 아츠', val: 41 } },
  { id: 'gear_31', name: '열 작업용 온도 측정기', part: 'component', set: 'set_heat_work', stat1: '지능', val1: 41, stat2: null, val2: 0, trait: { type: '배틀 스킬 피해', val: 41.4 } },
  { id: 'gear_32', name: '열 작업용 건틀릿 · I', part: 'glove', set: 'set_heat_work', stat1: '의지', val1: 65, stat2: '지능', val2: 43, trait: [{ type: '열기 피해', val: 19.2 }, { type: '자연 피해', val: 19.2 }] },
  { id: 'gear_33', name: '열 작업용 건틀릿', part: 'glove', set: 'set_heat_work', stat1: '지능', val1: 65, stat2: '힘', val2: 43, trait: [{ type: '열기 피해', val: 19.2 }, { type: '자연 피해', val: 19.2 }] },
  { id: 'gear_34', name: '열 작업용 강화 골격', part: 'armor', set: 'set_heat_work', stat1: '힘', val1: 87, stat2: '민첩', val2: 58, trait: [{ type: '열기 피해', val: 11.5 }, { type: '자연 피해', val: 11.5 }] },
  { id: 'gear_35', name: '개척자 증량 산소 공급 장치', part: 'component', set: 'set_pioneer', stat1: '민첩', val1: 32, stat2: '지능', val2: 21, trait: { type: '스탯', stat: '부스탯', val: 20.7 } },
  { id: 'gear_36', name: '개척자 통신기 · I', part: 'component', set: 'set_pioneer', stat1: '힘', val1: 32, stat2: '지능', val2: 21, trait: [{ type: '냉기 피해', val: 23 }, { type: '전기 피해', val: 23 }] },
  { id: 'gear_37', name: '개척자 통신기', part: 'component', set: 'set_pioneer', stat1: '힘', val1: 32, stat2: '민첩', val2: 21, trait: { type: '연계 스킬 피해', val: 41.4 } },
  { id: 'gear_38', name: '개척자 내부식성 장갑', part: 'glove', set: 'set_pioneer', stat1: '민첩', val1: 65, stat2: '지능', val2: 43, trait: { type: '배틀 스킬 피해', val: 34.5 } },
  { id: 'gear_39', name: '개척자 방어구 · III', part: 'armor', set: 'set_pioneer', stat1: '민첩', val1: 87, stat2: '지능', val2: 58, trait: { type: '스탯', stat: '부스탯', val: 10.4 } },
  { id: 'gear_40', name: '개척자 방어구 · II', part: 'armor', set: 'set_pioneer', stat1: '민첩', val1: 87, stat2: '지능', val2: 58, trait: { type: '배틀 스킬 피해', val: 20.7 } },
  { id: 'gear_41', name: '개척자 방어구 · I', part: 'armor', set: 'set_pioneer', stat1: '힘', val1: 87, stat2: '민첩', val2: 58, trait: { type: '배틀 스킬 피해', val: 20.7 } },
  { id: 'gear_42', name: '개척자 방어구', part: 'armor', set: 'set_pioneer', stat1: '힘', val1: 87, stat2: '지능', val2: 58, trait: { type: '궁극기 피해', val: 25.9 } },
  { id: 'gear_43', name: '펄스식 교정기', part: 'component', set: 'set_pulse', stat1: '지능', val1: 41, stat2: null, val2: 0, trait: { type: '오리지늄 아츠', val: 41 } },
  { id: 'gear_44', name: '펄스식 장갑', part: 'glove', set: 'set_pulse', stat1: '의지', val1: 65, stat2: '지능', val2: 43, trait: [{ type: '냉기 피해', val: 19.2 }, { type: '전기 피해', val: 19.2 }] },
  { id: 'gear_45', name: '펄스식 방해 슈트', part: 'armor', set: 'set_pulse', stat1: '지능', val1: 87, stat2: '의지', val2: 58, trait: { type: '오리지늄 아츠', val: 20 } },
  { id: 'gear_46', name: '본 크러셔 조각상 · I', part: 'component', set: 'set_bone_crusher', stat1: '의지', val1: 32, stat2: '지능', val2: 21, trait: { type: '연계 스킬 피해', val: 41.4 } },
  { id: 'gear_47', name: '본 크러셔 조각상', part: 'component', set: 'set_bone_crusher', stat1: '의지', val1: 32, stat2: '민첩', val2: 21, trait: { type: '배틀 스킬 피해', val: 41.4 } },
  { id: 'gear_48', name: '본 크러셔 마스크 · I', part: 'component', set: 'set_bone_crusher', stat1: '의지', val1: 32, stat2: '지능', val2: 21, trait: { type: '치명타 확률', val: 10.4 } },
  { id: 'gear_49', name: '본 크러셔 마스크', part: 'component', set: 'set_bone_crusher', stat1: '민첩', val1: 32, stat2: '힘', val2: 21, trait: { type: '불균형 피해', val: 41.4 } },
  { id: 'gear_50', name: '본 크러셔 머플러 · I', part: 'armor', set: 'set_bone_crusher', stat1: '의지', val1: 87, stat2: '민첩', val2: 58, trait: { type: '궁극기 충전', val: 12.3 } },
  { id: 'gear_51', name: '본 크러셔 머플러', part: 'armor', set: 'set_bone_crusher', stat1: '의지', val1: 87, stat2: '힘', val2: 58, trait: { type: '연계 스킬 피해', val: 20.7 } },
  { id: 'gear_52', name: '본 크러셔 중갑 방어구 · I', part: 'armor', set: 'set_bone_crusher', stat1: '민첩', val1: 87, stat2: '힘', val2: 58, trait: { type: '연계 스킬 피해', val: 20.7 } },
  { id: 'gear_53', name: '본 크러셔 중갑 방어구', part: 'armor', set: 'set_bone_crusher', stat1: '민첩', val1: 87, stat2: '지능', val2: 58, trait: { type: '궁극기 충전', val: 12.3 } },
  { id: 'gear_54', name: '경량 초자연 안정판', part: 'component', set: 'set_light_super', stat1: '민첩', val1: 32, stat2: '힘', val2: 21, trait: { type: '오리지늄 아츠', val: 41 } },
  { id: 'gear_55', name: '경량 초자연 분석 반지', part: 'component', set: 'set_light_super', stat1: '힘', val1: 32, stat2: '의지', val2: 21, trait: { type: '물리 피해', val: 23 } },
  { id: 'gear_56', name: '경량 초자연 글러브', part: 'glove', set: 'set_light_super', stat1: '민첩', val1: 65, stat2: '힘', val2: 43, trait: { type: '오리지늄 아츠', val: 34 } },
  { id: 'gear_57', name: '경량 초자연 보호판', part: 'armor', set: 'set_light_super', stat1: '힘', val1: 87, stat2: '의지', val2: 58, trait: { type: '불균형 피해', val: 20.7 } },
  { id: 'gear_58', name: '생체 보조 보호 주사기', part: 'component', set: 'set_bio_support', stat1: '의지', val1: 41, stat2: null, val2: 0, trait: { type: '치유 효율', val: 20.7 } },
  { id: 'gear_59', name: '생체 보조 보호판', part: 'component', set: 'set_bio_support', stat1: '의지', val1: 32, stat2: '지능', val2: 21, trait: { type: '스탯', stat: '주스탯', val: 20.7 } },
  { id: 'gear_60', name: '생체 보조 접속기 · I', part: 'component', set: 'set_bio_support', stat1: '힘', val1: 32, stat2: '의지', val2: 21, trait: { type: '최대 체력', val: 41.4 } },
  { id: 'gear_61', name: '생체 보조 접속기', part: 'component', set: 'set_bio_support', stat1: '힘', val1: 32, stat2: '의지', val2: 21, trait: { type: '모든 피해 감소', val: 17.2 } },
  { id: 'gear_62', name: '생체 보조 건틀릿', part: 'glove', set: 'set_bio_support', stat1: '의지', val1: 65, stat2: '힘', val2: 43, trait: { type: '치유 효율', val: 17.3 } },
  { id: 'gear_63', name: '생체 보조 견갑', part: 'glove', set: 'set_bio_support', stat1: '힘', val1: 65, stat2: '의지', val2: 43, trait: { type: '궁극기 충전', val: 20.5 } },
  { id: 'gear_64', name: '생체 보조 흉갑', part: 'armor', set: 'set_bio_support', stat1: '의지', val1: 87, stat2: '지능', val2: 58, trait: { type: '치유 효율', val: 10.4 } },
  { id: 'gear_65', name: '생체 보조 중갑', part: 'armor', set: 'set_bio_support', stat1: '힘', val1: 87, stat2: '의지', val2: 58, trait: { type: '치유 효율', val: 10.4 } },
  { id: 'gear_66', name: '홍산 부싯돌', part: 'component', set: 'set_swordsman', stat1: '민첩', val1: 32, stat2: '힘', val2: 21, trait: { type: '물리 피해', val: 23 } },
  { id: 'gear_67', name: '홍산 전술 건틀릿', part: 'glove', set: 'set_swordsman', stat1: '민첩', val1: 65, stat2: '힘', val2: 43, trait: { type: '궁극기 피해', val: 43.1 } },
  { id: 'gear_68', name: '홍산 전술 장갑', part: 'glove', set: 'set_swordsman', stat1: '힘', val1: 65, stat2: '의지', val2: 43, trait: { type: '물리 피해', val: 19.2 } },
  { id: 'gear_69', name: '홍산 중장갑', part: 'armor', set: 'set_swordsman', stat1: '민첩', val1: 87, stat2: '힘', val2: 58, trait: { type: '오리지늄 아츠', val: 20 } },
  { id: 'gear_70', name: '위기 탈출 도장 · I', part: 'component', set: 'set_crisis', stat1: '의지', val1: 43, stat2: null, val2: 0, trait: { type: '치명타 확률', val: 10.8 } },
  { id: 'gear_71', name: '위기 탈출 도장', part: 'component', set: 'set_crisis', stat1: '지능', val1: 43, stat2: null, val2: 0, trait: { type: '궁극기 충전', val: 25.7 } },
  { id: 'gear_72', name: '위기 탈출 식별 패널 · I', part: 'component', set: 'set_crisis', stat1: '민첩', val1: 43, stat2: null, val2: 0, trait: { type: '연계 스킬 피해', val: 43.2 } },
  { id: 'gear_73', name: '위기 탈출 식별 패널', part: 'component', set: 'set_crisis', stat1: '힘', val1: 43, stat2: null, val2: 0, trait: { type: '모든 피해 감소', val: 17.8 } }
];

const DATA_SETS = [
  { id: 'set_shikyang', name: '식양의 숨결', effect: { desc: '3개 세트 효과: 장착자의 생명력 +1000\n장착자가 증폭, 비호, 취약, 허약을 부여한 후, 다른 팀원이 주는 피해 +16%, 15초 동안 지속. 해당 효과는 중첩되지 않습니다.' } },
  { id: 'set_joryu', name: '조류의 물결', effect: { desc: '3개 세트 효과: 장착자의 모든 스킬 피해 +20%\n장착자가 적에게 2스택 혹은 그 이상의 아츠 부착을 부여한 후, 주는 아츠 피해 +35%, 15초 동안 지속. 해당 효과는 중첩되지 않습니다.' } },
  { id: 'set_eungryong', name: '응룡 50식', effect: { desc: '3개 세트 효과: 장착자의 공격력 +15%\n팀 내 임의의 오퍼레이터가 배틀 스킬을 사용할 때, 장착자가 응룡의 예리함 1스택 획득, 해당 오퍼레이터의 다음 연계 스킬 피해 +20%. 응룡의 예리함은 최대 3스택까지만 중첩됩니다.' } },
  { id: 'set_mi_police', name: 'M. I. 경찰용', effect: { desc: '3개 세트 효과: 장착자의 치명타 확률 +5%\n장착자가 적에게 치명타를 준 후, 5초 동안 공격력 +5%, 최대 중첩 5스택. 최대 중첩 시, 치명타 확률 추가 +5%, 해당 효과는 중첩되지 않습니다.' } },
  { id: 'set_heat_work', name: '열 작업용', effect: { desc: '3개 세트 효과: 장착자의 오리지늄 아츠 강도 +30\n장착자가 적에게 연소를 부여한 후, 열기 피해 +50%, 10초 동안 지속, 해당 효과는 중첩되지 않습니다.\n장착자가 적에게 부식을 부여한 후, 자연 피해 +50%, 10초 동안 지속, 해당 효과는 중첩되지 않습니다.' } },
  { id: 'set_pioneer', name: '개척', effect: { desc: '3개 세트 효과: 장착자의 연계 스킬 쿨타임 감소 +15%\n장착자가 스킬을 사용하여 스킬 게이지를 회복한 후, 팀 전체가 주는 피해 +16%, 15초 동안 지속. 해당 효과는 30초마다 최대 1회만 발동합니다.' } },
  { id: 'set_pulse', name: '펄스식', effect: { desc: '3개 세트 효과: 장착자의 오리지늄 아츠 강도 +30\n장착자가 적에게 감전을 부여한 후, 전기 피해 +50%, 10초 동안 지속, 해당 효과는 중첩되지 않습니다.\n장착자가 적에게 동결을 부여한 후, 냉기 피해 +50%, 10초 동안 지속, 해당 효과는 중첩되지 않습니다.' } },
  { id: 'set_bone_crusher', name: '본 크러셔', effect: { desc: '3개 세트 효과: 장착자의 공격력 +15%\n장착자가 연계 스킬을 사용할 때, 본 크러셔의 압박 1스택 획득, 다음 배틀 스킬의 피해 +30%. 본 크러셔의 압박은 최대 2스택까지만 중첩됩니다.' } },
  { id: 'set_light_super', name: '경량 초자연', effect: { desc: '3개 세트 효과: 장착자의 공격력 +8%\n장착자가 적에게 방어 불능을 부여한 후, 물리 피해 +8%, 15초 동안 지속, 최대 중첩 4스택. 목표의 방어 불능 스택이 4스택에 도달할 경우, 추가 물리 피해 +16%, 10초 동안 지속, 해당 효과는 중첩되지 않습니다.' } },
  { id: 'set_bio_support', name: '생체 보조', effect: { desc: '3개 세트 효과: 장착자의 치유 효율 +20%\n장착자가 아군을 치유할 때, 목표가 10초 동안 받는 모든 유형 피해 -15%, 해당 목표가 받는 치유량이 최대치를 넘을 경우, 받는 모든 유형 피해 -30%, 해당 효과는 중첩되지 않습니다.' } },
  { id: 'set_swordsman', name: '검술사', effect: { desc: '3개 세트 효과: 장착자의 불균형 효율 보너스 +20%\n장착자가 물리 이상 효과를 부여한 후, 공격력 250%만큼의 추가 물리 피해[10포인트 불균형치]. 해당 효과는 15초마다 최대 1회만 발동합니다.' } },
  { id: 'set_crisis', name: '위기 탈출', effect: { desc: '세트 효과가 없는 장비.' } }
];
